name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: ./.github/workflows/general-stale.yml
    with:
      dry-run: true
      stale-days: 1
      close-days: 1

  release-please:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: ./.github/workflows/general-release-please.yml
    with:
      dry-run: true
      config-file: examples/hello/release-please-config.json
      manifest-file: examples/hello/release-please-manifest.json

