name: DevOps / PR Labeler

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-labeler.yml@8bf36c075ec2050d3174a7872bcda21a9cc78b58 # main
    with:
      rules-json: |-
        [
          {"label":"ci","patterns":[".github/workflows/**",".github/actions/**"]},
          {"label":"security","patterns":[".gitleaks.toml",".trivyignore*",".github/dependabot.yml"]},
          {"label":"scripts","patterns":["scripts/**","Makefile","lefthook.yml"]},
          {"label":"docs","patterns":["**/*.md"]}
        ]
