name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: ./.github/workflows/general-semantic-pr.yml
    with:
      require-scope: false

  commit-messages:
    permissions:
      contents: read
    uses: ./.github/workflows/general-commit-messages.yml
    with:
      require-scope: false

  pr-summary:
    if: github.event.action == 'opened'
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/general-pr-summary.yml

  actionlint:
    permissions:
      contents: read
    uses: ./.github/workflows/general-actionlint.yml
    with:
      working-directory: "."
